<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Taller: Análisis Inicial de Datos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="aid_taller_solucionario_files/libs/clipboard/clipboard.min.js"></script>
<script src="aid_taller_solucionario_files/libs/quarto-html/quarto.js"></script>
<script src="aid_taller_solucionario_files/libs/quarto-html/popper.min.js"></script>
<script src="aid_taller_solucionario_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="aid_taller_solucionario_files/libs/quarto-html/anchor.min.js"></script>
<link href="aid_taller_solucionario_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="aid_taller_solucionario_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="aid_taller_solucionario_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="aid_taller_solucionario_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="aid_taller_solucionario_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Taller: Análisis Inicial de Datos</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>Vamos a resolver una serie de ejercicios de análisis inicial de datos y manejo de datos. Para esto, vamos a hacer uso de la base de datos <code>maca_meno_perclin_modif.xlsx</code>. Esta es una base de datos simulada y modificada para los fines de este ejercicio, la cual se basa en el estudio <strong>“Effect of a natural supplement containing glucosinolates, phytosterols and citrus flavonoids on body weight and metabolic parameters in a menopausal murine model induced by bilateral ovariectomy”</strong> publicado en la revista <strong>Gynecological Endocrinology</strong> en 2020. El experimento detallado puede leerse en el artículo original el cual se encuentra en este <a href="https://doi.org/10.1080/09513590.2020.1821639">enlace web</a>.</p>
<p>Este fue un experimento para evaluar el efecto de un <strong>suplemento</strong> basado en una preparación herbal que contiene glucosinolatos, fitosteroles y citrus flavonoides en desenlaces metabólicos usalmente afectados por la menopausia: peso, colesterol, triglicéridos, glucosa e índice glucosa / triglicéridos. La pregunta PICO es la siguiente:</p>
<p><strong>P:</strong> Ratones sometidos a ovarectomía bilateral mediante un modelo animal de menopausia quirúrgica.</p>
<p><strong>I1:</strong> Suplemento oral 0.5625 mg/kg/día administrada por vía oral</p>
<p><strong>I2:</strong> Suplemento oral 1.6875 mg/kg/día administrada por vía oral</p>
<p><strong>C1:</strong> Extracto de maca gelatinizada 0.5625 mg/kg/día administrada por vía oral</p>
<p><strong>C2:</strong> Solución salina 100 µl/kg/día por vía oral</p>
<p><strong>Os:</strong> Peso, colesterol, triglicéridos, glucosa e índice glucosa / triglicéridos.</p>
<p><strong>Control Sham</strong>: Hubo un control sham que recibió solución salina 100 µl/kg/día por vía oral y además fue sometido a una cirugía ficticia que no indujo menopausia quirúrgica.</p>
<p>El libro de códigos se encuentra en el mismo archivo excel, pero en otra hoja denominada <code>codebook</code>.</p>
<p>Hemos pre-escrito parte del código para facilitar el desarrollo del ejercicio y agregado algunos comentarios. Hemos dejado una línea en blanco ____ para solicitar que Ud. complete el ejercicio. Elimine la línea _____ y remplacela por su respuesta.</p>
</section>
<section id="cargar-paquetes" class="level2">
<h2 class="anchored" data-anchor-id="cargar-paquetes">Cargar paquetes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)  <span class="co"># Paquetes variados de universo tidyverse (dplyr, ggplot2, etc.)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)        <span class="co"># Para importar casi cualquier tipo de formato.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)      <span class="co"># Funcion skim() para explorar rápidamente variables categóricas y numéricas.</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)      <span class="co"># Proporciona función describe() que es muy similar a skim()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice
Loading required package: survival
Loading required package: Formula

Attaching package: 'Hmisc'

The following objects are masked from 'package:dplyr':

    src, summarize

The following objects are masked from 'package:base':

    format.pval, units</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)    <span class="co"># Miscelánea de funciones basadas en tidyverse para manejo y reporte de datos.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(visdat)     <span class="co"># Funciones para visualizar datos faltantes</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)      <span class="co"># FUnciones para manejo y limpieza de datos</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(VIM)        <span class="co"># Funciones para datos perdidos</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: colorspace
Loading required package: grid
VIM is ready to use.

Suggestions and bug-reports can be submitted at: https://github.com/statistikat/VIM/issues

Attaching package: 'VIM'

The following object is masked from 'package:datasets':

    sleep</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)     <span class="co"># Funciones para datos perdidos</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'naniar'

The following object is masked from 'package:skimr':

    n_complete</code></pre>
</div>
</div>
<p><strong>Nota:</strong> Recuerda instalar el paquete si no lo tienes hecho aún.</p>
</section>
<section id="importar-base-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="importar-base-de-datos">Importar base de datos</h2>
<p>Usaremos la navaja suiza de la importación de datos en R: el paquete {rio} y su función <code>import()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>preclin_data <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">"maca_meno_perclin_modif.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="paso-1-resumen-global-de-los-datos" class="level2">
<h2 class="anchored" data-anchor-id="paso-1-resumen-global-de-los-datos">Paso 1: Resumen global de los datos</h2>
<p>La función <code>glimpse()</code> (‘hechar un vistazo’) del paquete <code>{dplyr}</code> de <code>{tidyverse}</code> es muy útil para identificar rápidamente las características generales de los datos (número de filas, columnas y lista de variables con pequeña salida de ejemplo).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>preclin_data <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 26
Columns: 13
$ id_jaula     &lt;dbl&gt; 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 5, 5, 5, 5, 8, 8, 9, 9, 9, …
$ id_raton     &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17…
$ tratamiento  &lt;chr&gt; "control", "control", "control", "control", "control", "m…
$ protocolo    &lt;chr&gt; "ovx", "ovx", "ovx", "hemiovx", "ovx", "ovx", "ovx", "ovx…
$ peso_inicial &lt;dbl&gt; 26.00, 24.50, 20.40, 26.59, 23.50, 25.00, 24.80, 23.20, 2…
$ peso_final   &lt;dbl&gt; 33.28, 30.50, 29.93, 32.19, 30.37, 30.43, 28.77, 27.30, 2…
$ peso_utero   &lt;dbl&gt; 123.000, 0.063, 0.078, 0.134, 0.052, 0.055, 0.064, 0.062,…
$ chol         &lt;dbl&gt; 85.990, 94.460, 99.670, 83.380, 82.080, 107.490, 76.870, …
$ glucose      &lt;dbl&gt; 109.97, 81.62, 118.37, 71.91, 95.53, 160.36, 195.53, 182.…
$ tag          &lt;dbl&gt; 182.42, 211.87, 195.16, 98.46, 108.13, 141.10, 95.82, 105…
$ prot         &lt;dbl&gt; 43131.00, 4.68, NA, NA, 5.33, NA, 5.02, 6.12, NA, 4.85, -…
$ urea         &lt;dbl&gt; 66.27, 76.73, 52.32, 50.71, 26.02, NA, 40.78, 66.94, NA, …
$ album        &lt;dbl&gt; 66.82, 55.36, NA, NA, NA, 72.14, 67.09, 70.64, 66.27, 83.…</code></pre>
</div>
</div>
<p>Podemos usar también la función <code>skim()</code> del paquete <code>{skimr}</code> para tener un ersumen detallado de cada una de las variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>preclin_data <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">tratamiento</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">protocolo</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">id_jaula</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5.04</td>
<td style="text-align: right;">3.40</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">8.75</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: left;">▇▂▃▂▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">id_raton</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">10.81</td>
<td style="text-align: right;">7.21</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.25</td>
<td style="text-align: right;">10.50</td>
<td style="text-align: right;">16.75</td>
<td style="text-align: right;">23.00</td>
<td style="text-align: left;">▇▃▅▃▅</td>
</tr>
<tr class="odd">
<td style="text-align: left;">peso_inicial</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">23.77</td>
<td style="text-align: right;">2.14</td>
<td style="text-align: right;">18.90</td>
<td style="text-align: right;">22.55</td>
<td style="text-align: right;">23.50</td>
<td style="text-align: right;">25.23</td>
<td style="text-align: right;">27.90</td>
<td style="text-align: left;">▃▃▇▇▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">peso_final</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">28.83</td>
<td style="text-align: right;">2.30</td>
<td style="text-align: right;">23.80</td>
<td style="text-align: right;">27.30</td>
<td style="text-align: right;">28.77</td>
<td style="text-align: right;">30.27</td>
<td style="text-align: right;">33.28</td>
<td style="text-align: left;">▂▆▇▆▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">peso_utero</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.82</td>
<td style="text-align: right;">24.10</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">123.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">chol</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">82.83</td>
<td style="text-align: right;">12.85</td>
<td style="text-align: right;">59.28</td>
<td style="text-align: right;">74.26</td>
<td style="text-align: right;">83.38</td>
<td style="text-align: right;">88.59</td>
<td style="text-align: right;">107.49</td>
<td style="text-align: left;">▅▃▇▂▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">glucose</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">123.36</td>
<td style="text-align: right;">35.21</td>
<td style="text-align: right;">60.10</td>
<td style="text-align: right;">104.46</td>
<td style="text-align: right;">116.53</td>
<td style="text-align: right;">143.83</td>
<td style="text-align: right;">195.53</td>
<td style="text-align: left;">▃▇▇▃▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">tag</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">156.94</td>
<td style="text-align: right;">50.37</td>
<td style="text-align: right;">90.99</td>
<td style="text-align: right;">109.78</td>
<td style="text-align: right;">151.87</td>
<td style="text-align: right;">192.63</td>
<td style="text-align: right;">282.64</td>
<td style="text-align: left;">▇▃▇▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">prot</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.69</td>
<td style="text-align: right;">2177.95</td>
<td style="text-align: right;">10229.41</td>
<td style="text-align: right;">-999.00</td>
<td style="text-align: right;">4.70</td>
<td style="text-align: right;">4.97</td>
<td style="text-align: right;">5.36</td>
<td style="text-align: right;">43131.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">urea</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">57.78</td>
<td style="text-align: right;">29.34</td>
<td style="text-align: right;">26.02</td>
<td style="text-align: right;">40.78</td>
<td style="text-align: right;">52.32</td>
<td style="text-align: right;">66.27</td>
<td style="text-align: right;">157.89</td>
<td style="text-align: left;">▇▅▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">album</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">66.25</td>
<td style="text-align: right;">7.71</td>
<td style="text-align: right;">52.77</td>
<td style="text-align: right;">64.64</td>
<td style="text-align: right;">66.82</td>
<td style="text-align: right;">68.59</td>
<td style="text-align: right;">83.73</td>
<td style="text-align: left;">▂▂▇▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>O podemos usar la función <code>describe()</code> del paquete <code>{Hmisc}</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>preclin_data <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">describe</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>. 

 13  Variables      26  Observations
--------------------------------------------------------------------------------
id_jaula 
       n  missing distinct     Info     Mean      Gmd 
      26        0        8     0.98    5.038    3.905 

lowest :  1  2  3  5  7, highest:  5  7  8  9 10
                                                          
Value          1     2     3     5     7     8     9    10
Frequency      5     4     3     4     1     2     4     3
Proportion 0.192 0.154 0.115 0.154 0.038 0.077 0.154 0.115
--------------------------------------------------------------------------------
id_raton 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      26        0       23    0.998    10.81    8.452     1.00     1.50 
     .25      .50      .75      .90      .95 
    4.25    10.50    16.75    20.50    21.75 

lowest :  1  2  3  4  5, highest: 19 20 21 22 23
--------------------------------------------------------------------------------
tratamiento 
       n  missing distinct 
      26        0        5 

lowest : control                   maca                      maca + critro             sham operated             triple dosis maca + citro
highest: control                   maca                      maca + critro             sham operated             triple dosis maca + citro

control (8, 0.308), maca (5, 0.192), maca + critro (4, 0.154), sham operated
(4, 0.154), triple dosis maca + citro (5, 0.192)
--------------------------------------------------------------------------------
protocolo 
       n  missing distinct 
      26        0        4 
                                                          
Value      desconocido     hemiovx      no ovx         ovx
Frequency            2           2           4          18
Proportion       0.077       0.077       0.154       0.692
--------------------------------------------------------------------------------
peso_inicial 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      26        0       20    0.998    23.77    2.449    20.40    21.15 
     .25      .50      .75      .90      .95 
   22.55    23.50    25.23    26.30    26.90 

lowest : 18.90 20.40 21.90 22.40 22.50, highest: 25.50 26.00 26.59 27.00 27.90
                                                                            
Value      18.90 20.40 21.90 22.40 22.50 22.69 22.90 23.20 23.40 23.50 23.90
Frequency      1     2     2     1     1     1     1     1     2     2     1
Proportion 0.038 0.077 0.077 0.038 0.038 0.038 0.038 0.038 0.077 0.077 0.038
                                                                
Value      24.50 24.80 25.00 25.30 25.50 26.00 26.59 27.00 27.90
Frequency      2     1     1     1     1     2     1     1     1
Proportion 0.077 0.038 0.038 0.038 0.038 0.077 0.038 0.038 0.038
--------------------------------------------------------------------------------
peso_final 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      25        1       21    0.998    28.83    2.617    25.28    26.69 
     .25      .50      .75      .90      .95 
   27.30    28.77    30.27    31.51    33.06 

lowest : 23.80 24.93 26.68 26.70 26.86, highest: 30.37 30.43 30.50 32.19 33.28
--------------------------------------------------------------------------------
peso_utero 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      26        0       24    0.999    4.819    9.521  0.01750  0.03400 
     .25      .50      .75      .90      .95 
 0.05825  0.07300  0.08900  0.15500  0.44525 

lowest :   0.014   0.016   0.022   0.046   0.052
highest:   0.113   0.134   0.176   0.535 123.000
                                  
Value        0.0   0.2   0.6 123.0
Frequency     20     4     1     1
Proportion 0.769 0.154 0.038 0.038

For the frequency table, variable is rounded to the nearest 0.2
--------------------------------------------------------------------------------
chol 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      25        1       21    0.998    82.83    14.86    64.68    66.31 
     .25      .50      .75      .90      .95 
   74.26    83.38    88.59    99.67   103.84 

lowest :  59.28  64.40  65.79  67.10  68.40, highest:  94.46  95.76  99.67 104.88 107.49
--------------------------------------------------------------------------------
glucose 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      26        0       23    0.998    123.4    40.35    73.49    79.92 
     .25      .50      .75      .90      .95 
  104.46   116.53   143.83   175.45   183.98 

lowest :  60.10  71.91  78.22  81.62  94.23, highest: 160.36 168.50 182.41 184.51 195.53
--------------------------------------------------------------------------------
tag 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      26        0       22    0.998    156.9    57.44    93.85    97.14 
     .25      .50      .75      .90      .95 
  109.78   151.87   192.63   205.94   236.60 

lowest :  90.99  93.19  95.82  98.46 105.49, highest: 199.12 200.00 211.87 244.84 282.64
--------------------------------------------------------------------------------
prot 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      18        8       12    0.987     2178     5160 -999.000 -999.000 
     .25      .50      .75      .90      .95 
   4.705    4.975    5.360    6.135 6474.894 

lowest :  -999.00     4.68     4.78     4.85     4.93
highest:     5.33     5.37     6.12     6.17 43131.00
                                                                         
Value       -999.00     4.68     4.78     4.85     4.93     5.02     5.15
Frequency         4        1        1        1        2        1        1
Proportion    0.222    0.056    0.056    0.056    0.111    0.056    0.056
                                                       
Value          5.33     5.37     6.12     6.17 43131.00
Frequency         2        2        1        1        1
Proportion    0.111    0.111    0.056    0.056    0.056
--------------------------------------------------------------------------------
urea 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      17        9       14    0.994    57.78    27.46    32.79    36.57 
     .25      .50      .75      .90      .95 
   40.78    52.32    66.27    70.86    92.96 

lowest :  26.02  34.48  37.96  38.23  40.78, highest:  60.37  66.27  66.94  76.73 157.89
                                                                         
Value       26.02  34.48  37.96  38.23  40.78  43.06  45.61  50.71  52.32
Frequency       1      1      1      1      1      1      1      1      2
Proportion  0.059  0.059  0.059  0.059  0.059  0.059  0.059  0.059  0.118
                                             
Value       60.37  66.27  66.94  76.73 157.89
Frequency       1      3      1      1      1
Proportion  0.059  0.176  0.059  0.059  0.059
--------------------------------------------------------------------------------
album 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      13       13       11    0.989    66.25    8.394    54.32    56.21 
     .25      .50      .75      .90      .95 
   64.64    66.82    68.59    71.84    76.78 

lowest : 52.77 55.36 59.59 64.64 66.27, highest: 67.09 68.59 70.64 72.14 83.73
                                                                            
Value      52.77 55.36 59.59 64.64 66.27 66.82 67.09 68.59 70.64 72.14 83.73
Frequency      1     1     1     1     1     3     1     1     1     1     1
Proportion 0.077 0.077 0.077 0.077 0.077 0.231 0.077 0.077 0.077 0.077 0.077
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
</section>
<section id="paso-2-detecte-y-maneje-duplicados" class="level2">
<h2 class="anchored" data-anchor-id="paso-2-detecte-y-maneje-duplicados">Paso 2: Detecte y maneje duplicados</h2>
<p>La primera pregunta que debemos hacernos con esta base de datos es <strong>¿cuál es la variable ID que debe ser única?</strong> Si bien hay dos variables id: <code>id_jaula</code> y <code>id_raton</code>, solo <code>id_raton</code> es la variable que debería ser única, ya que varios ratones podían compartir la misma jaula como parte del experimento.</p>
<p>Una forma muy informal de buscar datos duplicados es inspeccionado en data frame con la función <code>View()</code> de R base o dándole click al ícono de matriz de cálculo que aparece a la derecha del objeto <code>preclin_data</code> mostrado en el <code>Environment</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>preclin_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id_jaula id_raton               tratamiento   protocolo peso_inicial
1         1        1                   control         ovx        26.00
2         1        2                   control         ovx        24.50
3         1        3                   control         ovx        20.40
4         2        4                   control     hemiovx        26.59
5         2        5                   control         ovx        23.50
6         2        6                      maca         ovx        25.00
7         2        7                      maca         ovx        24.80
8         3        8                      maca         ovx        23.20
9         3        9                      maca     hemiovx        22.69
10        3       10                      maca         ovx        23.90
11        5       11             maca + critro desconocido        21.90
12        5       12             maca + critro         ovx        23.40
13        5       13             maca + critro         ovx        21.90
14        5       14             maca + critro         ovx        22.40
15        8       15 triple dosis maca + citro         ovx        18.90
16        8       16 triple dosis maca + citro         ovx        23.50
17        9       17 triple dosis maca + citro         ovx        24.50
18        9       18 triple dosis maca + citro         ovx        25.30
19        9       19 triple dosis maca + citro         ovx        27.90
20        9       20             sham operated      no ovx        25.50
21       10       21             sham operated      no ovx        23.40
22       10       22             sham operated      no ovx        22.50
23       10       23             sham operated      no ovx        22.90
24        1        1                   control desconocido        26.00
25        1        3                   control         ovx        20.40
26        7        1                   control         ovx        27.00
   peso_final peso_utero    chol glucose    tag     prot   urea album
1       33.28    123.000  85.990  109.97 182.42 43131.00  66.27 66.82
2       30.50      0.063  94.460   81.62 211.87     4.68  76.73 55.36
3       29.93      0.078  99.670  118.37 195.16       NA  52.32    NA
4       32.19      0.134  83.380   71.91  98.46       NA  50.71    NA
5       30.37      0.052  82.080   95.53 108.13     5.33  26.02    NA
6       30.43      0.055 107.490  160.36 141.10       NA     NA 72.14
7       28.77      0.064  76.870  195.53  95.82     5.02  40.78 67.09
8       27.30      0.062  95.760  182.41 105.49     6.12  66.94 70.64
9       26.86      0.070  85.340  184.51  90.99       NA     NA 66.27
10      29.10      0.113  82.080  168.50 143.30     4.85  34.48 83.73
11      24.93      0.108  80.781  113.38 128.35  -999.00     NA    NA
12      26.70      0.022  88.590  102.62 282.64  -999.00     NA    NA
13      28.67      0.014 104.880   60.10 200.00     5.33  37.96    NA
14      28.37      0.046  70.350  150.13 199.12     4.93  45.61 64.64
15      23.80      0.057  78.170  110.50 114.73     4.78  38.23 52.77
16      26.70      0.065  85.340  144.88 134.51     5.15  43.06 59.59
17      28.77      0.016  64.400  138.85 160.44  -999.00     NA    NA
18      29.20      0.068  67.100  140.68 127.03  -999.00     NA    NA
19      29.48      0.076  65.790  114.70 169.67     6.17     NA    NA
20      30.27      0.088  74.260   94.23 185.05     4.93     NA 68.59
21      27.90      0.535  59.280  126.77 244.84       NA  60.37    NA
22      26.68      0.081  68.400   78.22  93.19       NA 157.89    NA
23      27.43      0.176  84.690  125.20 108.13       NA     NA    NA
24      33.28      0.089  85.990  109.97 182.42     5.37  66.27 66.82
25      29.93      0.078  99.670  118.37 195.16       NA  52.32    NA
26         NA      0.089      NA  109.97 182.42     5.37  66.27 66.82</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(preclin_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>De la inspección de esta matriz de cálculo, podemos apreciar que efectivamente hay datos duplicados. Si bien esta forma puede ayudar cuand los datos son de tamaño pequeño y manejable, no es útil cuando se tienen muchísimos datos. Se necesita un método que detecte todos los duplicados sin posibilidad de que se escape algún duplicado.</p>
<p>Para esto, podemos usar la función <code>get_dupes()</code> del paquete <code>{janitor}</code>, el cual permite hacer el diagnóstico de observaciones duplicadas en todo el conjunto de datos.</p>
<p>Lo primero es identificar si hay algún duplicado de observación completa, es decir, que hayan dos o más filas que sean exactamente iguales entre sí en todas sus variables. Esta es la forma mas obvia de duplicación de datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>preclin_data <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dupes</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>No variable names specified - using all columns.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  id_jaula id_raton tratamiento protocolo peso_inicial peso_final peso_utero
1        1        3     control       ovx         20.4      29.93      0.078
2        1        3     control       ovx         20.4      29.93      0.078
   chol glucose    tag prot  urea album dupe_count
1 99.67  118.37 195.16   NA 52.32    NA          2
2 99.67  118.37 195.16   NA 52.32    NA          2</code></pre>
</div>
</div>
<p>Se observa que hay duplicados de fila, por lo que uno puede proceder a eliminarlos sin ninguna preocupación. Al ser filas exactamente iguales, no importa cuál de las filas elimine, solo necesito quedarme con una de estas. Es muy importante guardar el data frame para poder seguir limpiando sobre este:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>preclin_data <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(<span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="ot">-&gt;</span> preclin_data2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Una forma más sutil es cuando solo hay duplicación del ID pero no de la fila entera. En estos casos la pregunta que surge es ¿qué fila es la correcta? En esta base de datos podemos verificar este tipo de duplicación también haciendo uso de <code>get_dupes()</code> e indicando la o las variables donde se desea identificar el duplicado.</p>
<p>Veamos si todavía hay duplicados en la base de datos. Trabajaremos sobre el data frame nuevo <code>preclin_data2</code> al cual ya se le quitaron los duplicados de fila completa.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>preclin_data2 <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dupes</span>(id_raton)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id_raton dupe_count id_jaula tratamiento   protocolo peso_inicial peso_final
1        1          3        1     control         ovx           26      33.28
2        1          3        1     control desconocido           26      33.28
3        1          3        7     control         ovx           27         NA
  peso_utero  chol glucose    tag     prot  urea album
1    123.000 85.99  109.97 182.42 43131.00 66.27 66.82
2      0.089 85.99  109.97 182.42     5.37 66.27 66.82
3      0.089    NA  109.97 182.42     5.37 66.27 66.82</code></pre>
</div>
</div>
<p>Se aprecia que el ratón con id_raton de 1 se repite 3 veces pero solo debería aparecer una vez. Además, a pesar de ser el mismo ratón, supuestamente, tiene valores distitntos para la variable id_jaula y la variable protocolo. La pregunta clave aquí es ¿cuál de todas las filas es la fila correcta y cuáles son filas que debamos eliminar? La solución requiere conocer los datos originales, verificar la fuente de los datos y otros elementos propios de la investigación.</p>
<p>Supongamos que luego de revisar los documentos fuente y hacer algunas otras validaciones, logras determinar que la fila correcta es la del raton que tiene protocolo = “ovx” y id_jaula = 1. Entonces, debes eliminar las otras dos filas equivocadas que son duplicados de ratón pero con datos erróneos. Podemos hacer esto usando la función <code>filter()</code>. No se olviden de guardar los datos para poder trabajar con los datos nuevos sin duplicados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>preclin_data2 <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(id_raton <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> protocolo <span class="sc">==</span> <span class="st">"desconocido"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(id_raton <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> id_jaula <span class="sc">==</span> <span class="dv">7</span>)) <span class="ot">-&gt;</span> preclin_data3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="paso-3-datos-faltantes" class="level2">
<h2 class="anchored" data-anchor-id="paso-3-datos-faltantes">Paso 3: Datos faltantes</h2>
<section id="paso-3.1-identifique-datos-faltantes" class="level3">
<h3 class="anchored" data-anchor-id="paso-3.1-identifique-datos-faltantes">Paso 3.1: Identifique datos faltantes</h3>
<p>Podemos usar <code>skim()</code> para hacernos una idea de los datos faltantes. Aplicaremos esta función sobre el data frame sin duplicados que creamos anteriormente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>preclin_data3 <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">tratamiento</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">protocolo</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">id_jaula</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5.30</td>
<td style="text-align: right;">3.38</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: left;">▇▃▅▂▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">id_raton</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">6.78</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">6.50</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">17.50</td>
<td style="text-align: right;">23.00</td>
<td style="text-align: left;">▇▆▇▆▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">peso_inicial</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">23.68</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: right;">18.90</td>
<td style="text-align: right;">22.59</td>
<td style="text-align: right;">23.50</td>
<td style="text-align: right;">24.90</td>
<td style="text-align: right;">27.90</td>
<td style="text-align: left;">▂▃▇▇▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">peso_final</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">28.59</td>
<td style="text-align: right;">2.18</td>
<td style="text-align: right;">23.80</td>
<td style="text-align: right;">27.08</td>
<td style="text-align: right;">28.77</td>
<td style="text-align: right;">30.10</td>
<td style="text-align: right;">33.28</td>
<td style="text-align: left;">▂▆▇▅▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">peso_utero</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5.44</td>
<td style="text-align: right;">25.63</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">123.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">chol</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">81.96</td>
<td style="text-align: right;">12.89</td>
<td style="text-align: right;">59.28</td>
<td style="text-align: right;">72.31</td>
<td style="text-align: right;">82.08</td>
<td style="text-align: right;">87.29</td>
<td style="text-align: right;">107.49</td>
<td style="text-align: left;">▅▃▇▃▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">glucose</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">124.74</td>
<td style="text-align: right;">37.27</td>
<td style="text-align: right;">60.10</td>
<td style="text-align: right;">99.08</td>
<td style="text-align: right;">118.37</td>
<td style="text-align: right;">147.50</td>
<td style="text-align: right;">195.53</td>
<td style="text-align: left;">▅▇▇▃▅</td>
</tr>
<tr class="even">
<td style="text-align: left;">tag</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">153.06</td>
<td style="text-align: right;">52.36</td>
<td style="text-align: right;">90.99</td>
<td style="text-align: right;">108.13</td>
<td style="text-align: right;">141.10</td>
<td style="text-align: right;">190.11</td>
<td style="text-align: right;">282.64</td>
<td style="text-align: left;">▇▃▅▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">prot</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">2449.52</td>
<td style="text-align: right;">10857.48</td>
<td style="text-align: right;">-999.00</td>
<td style="text-align: right;">-246.24</td>
<td style="text-align: right;">4.93</td>
<td style="text-align: right;">5.33</td>
<td style="text-align: right;">43131.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">urea</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">56.95</td>
<td style="text-align: right;">32.34</td>
<td style="text-align: right;">26.02</td>
<td style="text-align: right;">38.87</td>
<td style="text-align: right;">48.16</td>
<td style="text-align: right;">64.80</td>
<td style="text-align: right;">157.89</td>
<td style="text-align: left;">▇▃▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">album</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">66.15</td>
<td style="text-align: right;">8.44</td>
<td style="text-align: right;">52.77</td>
<td style="text-align: right;">62.12</td>
<td style="text-align: right;">66.82</td>
<td style="text-align: right;">69.62</td>
<td style="text-align: right;">83.73</td>
<td style="text-align: left;">▃▃▇▂▂</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>También podemos hacer uso de gráficos de datos faltantes para mejorar la comprensión de estos. La función <code>vis_dat()</code> del paquete <code>{vis_dat}</code> ofrece buenas soluciones gráficas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>preclin_data3 <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vis_dat</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `gather_()` was deprecated in tidyr 1.2.0.
Please use `gather()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="aid_taller_solucionario_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Otra función muy útil es <code>vis_miss()</code> que te da el porcentaje de datos faltantes por variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>preclin_data3 <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vis_miss</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="aid_taller_solucionario_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Si queremos ver cómo se combinan los datos faltantes por variable, la librería <code>{VIM}</code> ofrece la función <code>aggr()</code> que permite una rápida visualización.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>preclin_data3 <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aggr</span>(<span class="at">numbers =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="aid_taller_solucionario_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>También podemos usar la función <code>gg_miss_upset()</code> del paquete <code>{naniar}</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>preclin_data3 <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gg_miss_upset</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="aid_taller_solucionario_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Podemos inspeccionar los datos solo de los individuos con datos faltantes usando <code>filter()</code>. Por ejemplo, si queremos saber quienes son los individuos que tienen datos faltantes en la variable urea, podemos hacerlo fácilmente usando <code>is.na()</code> dentro de <code>filter()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>preclin_data3 <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(urea))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id_jaula id_raton               tratamiento   protocolo peso_inicial
1        2        6                      maca         ovx        25.00
2        3        9                      maca     hemiovx        22.69
3        5       11             maca + critro desconocido        21.90
4        5       12             maca + critro         ovx        23.40
5        9       17 triple dosis maca + citro         ovx        24.50
6        9       18 triple dosis maca + citro         ovx        25.30
7        9       19 triple dosis maca + citro         ovx        27.90
8        9       20             sham operated      no ovx        25.50
9       10       23             sham operated      no ovx        22.90
  peso_final peso_utero    chol glucose    tag    prot urea album
1      30.43      0.055 107.490  160.36 141.10      NA   NA 72.14
2      26.86      0.070  85.340  184.51  90.99      NA   NA 66.27
3      24.93      0.108  80.781  113.38 128.35 -999.00   NA    NA
4      26.70      0.022  88.590  102.62 282.64 -999.00   NA    NA
5      28.77      0.016  64.400  138.85 160.44 -999.00   NA    NA
6      29.20      0.068  67.100  140.68 127.03 -999.00   NA    NA
7      29.48      0.076  65.790  114.70 169.67    6.17   NA    NA
8      30.27      0.088  74.260   94.23 185.05    4.93   NA 68.59
9      27.43      0.176  84.690  125.20 108.13      NA   NA    NA</code></pre>
</div>
</div>
</section>
<section id="paso-3.2-manejo-de-los-datos-faltantes" class="level3">
<h3 class="anchored" data-anchor-id="paso-3.2-manejo-de-los-datos-faltantes">Paso 3.2: Manejo de los datos faltantes</h3>
<p>Imaginemos que sabemos que el ratón con <code>id == 6</code> tiene un valor de úrea <code>65.2</code>. Como vemos en la tabla de datos de arriba, ese valor está faltando. Nosotros podemos corregir este valor usando código. Para esto podemos hacer uso de la función <code>replace()</code> tal y como sigue:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>preclin_data3 <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">urea =</span> <span class="fu">replace</span>(urea, id_raton <span class="sc">==</span> <span class="dv">6</span>, <span class="fl">65.2</span>)) <span class="ot">-&gt;</span> preclin_data4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Otro problema clásico en el análisis inicial de datos y su limpieza es que encontramos valores perdidos camuflados, que no parecen perdidos a menos que uno los inspeccione detalladamente. Por ejemplo, veamos qué pasa con estas dos variables <code>prot</code> y <code>protocolo</code>.</p>
<p>Notar que estas hay valores perdidos que han sido etiquetados como <code>-999</code> o <code>desconocido</code> respectivamente. Estos valores deberían ser transformados <code>NA</code> para que R los considere datos faltantes. Esto se puede lograr fácilmente usando la función <code>na_if()</code> del paquete <code>{tidyr}</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>preclin_data4 <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na_if</span>(<span class="fu">list</span>(<span class="at">prot =</span> <span class="sc">-</span><span class="dv">999</span>)) <span class="ot">-&gt;</span> preclin_data5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>preclin_data5 <span class="sc">%&gt;%</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">na_if</span>(<span class="fu">list</span>(<span class="at">protocolo =</span> <span class="st">"desconocido"</span>)) <span class="ot">-&gt;</span> preclin_data6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>preclin_data4 <span class="sc">%&gt;%</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na_if</span>(<span class="fu">list</span>(<span class="at">prot =</span> <span class="sc">-</span><span class="dv">999</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na_if</span>(<span class="fu">list</span>(<span class="at">protocolo =</span> <span class="st">"desconocido"</span>)) <span class="ot">-&gt;</span> preclin_data7</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="paso-4-valores-extremos-no-plausibles" class="level2">
<h2 class="anchored" data-anchor-id="paso-4-valores-extremos-no-plausibles">Paso 4: Valores extremos no plausibles</h2>
<p>Para identificar valores extremos no plausibles, puede ayudar ver los valores mínimos y máximo usando <code>skim()</code> o <code>describe()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>preclin_data7 <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">tratamiento</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">protocolo</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">id_jaula</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5.30</td>
<td style="text-align: right;">3.38</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: left;">▇▃▅▂▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">id_raton</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">6.78</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">6.50</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">17.50</td>
<td style="text-align: right;">23.00</td>
<td style="text-align: left;">▇▆▇▆▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">peso_inicial</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">23.68</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: right;">18.90</td>
<td style="text-align: right;">22.59</td>
<td style="text-align: right;">23.50</td>
<td style="text-align: right;">24.90</td>
<td style="text-align: right;">27.90</td>
<td style="text-align: left;">▂▃▇▇▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">peso_final</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">28.59</td>
<td style="text-align: right;">2.18</td>
<td style="text-align: right;">23.80</td>
<td style="text-align: right;">27.08</td>
<td style="text-align: right;">28.77</td>
<td style="text-align: right;">30.10</td>
<td style="text-align: right;">33.28</td>
<td style="text-align: left;">▂▆▇▅▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">peso_utero</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5.44</td>
<td style="text-align: right;">25.63</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">123.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">chol</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">81.96</td>
<td style="text-align: right;">12.89</td>
<td style="text-align: right;">59.28</td>
<td style="text-align: right;">72.31</td>
<td style="text-align: right;">82.08</td>
<td style="text-align: right;">87.29</td>
<td style="text-align: right;">107.49</td>
<td style="text-align: left;">▅▃▇▃▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">glucose</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">124.74</td>
<td style="text-align: right;">37.27</td>
<td style="text-align: right;">60.10</td>
<td style="text-align: right;">99.08</td>
<td style="text-align: right;">118.37</td>
<td style="text-align: right;">147.50</td>
<td style="text-align: right;">195.53</td>
<td style="text-align: left;">▅▇▇▃▅</td>
</tr>
<tr class="even">
<td style="text-align: left;">tag</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">153.06</td>
<td style="text-align: right;">52.36</td>
<td style="text-align: right;">90.99</td>
<td style="text-align: right;">108.13</td>
<td style="text-align: right;">141.10</td>
<td style="text-align: right;">190.11</td>
<td style="text-align: right;">282.64</td>
<td style="text-align: left;">▇▃▅▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">prot</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">3599.02</td>
<td style="text-align: right;">12449.34</td>
<td style="text-align: right;">4.68</td>
<td style="text-align: right;">4.91</td>
<td style="text-align: right;">5.08</td>
<td style="text-align: right;">5.53</td>
<td style="text-align: right;">43131.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">urea</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">57.50</td>
<td style="text-align: right;">31.23</td>
<td style="text-align: right;">26.02</td>
<td style="text-align: right;">39.50</td>
<td style="text-align: right;">50.71</td>
<td style="text-align: right;">65.74</td>
<td style="text-align: right;">157.89</td>
<td style="text-align: left;">▇▅▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">album</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">66.15</td>
<td style="text-align: right;">8.44</td>
<td style="text-align: right;">52.77</td>
<td style="text-align: right;">62.12</td>
<td style="text-align: right;">66.82</td>
<td style="text-align: right;">69.62</td>
<td style="text-align: right;">83.73</td>
<td style="text-align: left;">▃▃▇▂▂</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>preclin_data7 <span class="sc">%&gt;%</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">describe</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>. 

 13  Variables      23  Observations
--------------------------------------------------------------------------------
id_jaula 
       n  missing distinct     Info     Mean      Gmd 
      23        0        7    0.979    5.304    3.881 

lowest :  1  2  3  5  8, highest:  3  5  8  9 10
                                                    
Value          1     2     3     5     8     9    10
Frequency      3     4     3     4     2     4     3
Proportion 0.130 0.174 0.130 0.174 0.087 0.174 0.130
--------------------------------------------------------------------------------
id_raton 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      23        0       23        1       12        8      2.1      3.2 
     .25      .50      .75      .90      .95 
     6.5     12.0     17.5     20.8     21.9 

lowest :  1  2  3  4  5, highest: 19 20 21 22 23
--------------------------------------------------------------------------------
tratamiento 
       n  missing distinct 
      23        0        5 

lowest : control                   maca                      maca + critro             sham operated             triple dosis maca + citro
highest: control                   maca                      maca + critro             sham operated             triple dosis maca + citro

control (5, 0.217), maca (5, 0.217), maca + critro (4, 0.174), sham operated
(4, 0.174), triple dosis maca + citro (5, 0.217)
--------------------------------------------------------------------------------
protocolo 
       n  missing distinct 
      22        1        3 
                                  
Value      hemiovx  no ovx     ovx
Frequency        2       4      16
Proportion   0.091   0.182   0.727
--------------------------------------------------------------------------------
peso_inicial 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      23        0       19    0.998    23.68    2.244    20.55    21.90 
     .25      .50      .75      .90      .95 
   22.59    23.50    24.90    25.90    26.53 

lowest : 18.90 20.40 21.90 22.40 22.50, highest: 25.30 25.50 26.00 26.59 27.90
                                                                            
Value      18.90 20.40 21.90 22.40 22.50 22.69 22.90 23.20 23.40 23.50 23.90
Frequency      1     1     2     1     1     1     1     1     2     2     1
Proportion 0.043 0.043 0.087 0.043 0.043 0.043 0.043 0.043 0.087 0.087 0.043
                                                          
Value      24.50 24.80 25.00 25.30 25.50 26.00 26.59 27.90
Frequency      2     1     1     1     1     1     1     1
Proportion 0.087 0.043 0.043 0.043 0.043 0.043 0.043 0.043
--------------------------------------------------------------------------------
peso_final 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      23        0       21    0.999    28.59    2.483    25.11    26.68 
     .25      .50      .75      .90      .95 
   27.08    28.77    30.10    30.49    32.02 

lowest : 23.80 24.93 26.68 26.70 26.86, highest: 30.37 30.43 30.50 32.19 33.28
--------------------------------------------------------------------------------
peso_utero 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      23        0       23        1    5.437    10.76   0.0166   0.0268 
     .25      .50      .75      .90      .95 
  0.0560   0.0680   0.0980   0.1676   0.4991 

lowest :   0.014   0.016   0.022   0.046   0.052
highest:   0.113   0.134   0.176   0.535 123.000
                                  
Value        0.0   0.2   0.6 123.0
Frequency     17     4     1     1
Proportion 0.739 0.174 0.043 0.043

For the frequency table, variable is rounded to the nearest 0.2
--------------------------------------------------------------------------------
chol 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      23        0       21    0.999    81.96     14.9    64.54    66.05 
     .25      .50      .75      .90      .95 
   72.31    82.08    87.29    98.89   104.36 

lowest :  59.28  64.40  65.79  67.10  68.40, highest:  94.46  95.76  99.67 104.88 107.49
--------------------------------------------------------------------------------
glucose 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      23        0       23        1    124.7    43.44    72.54    78.90 
     .25      .50      .75      .90      .95 
   99.08   118.37   147.50   179.63   184.30 

lowest :  60.10  71.91  78.22  81.62  94.23, highest: 160.36 168.50 182.41 184.51 195.53
--------------------------------------------------------------------------------
tag 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      23        0       22        1    153.1    59.41    93.45    96.35 
     .25      .50      .75      .90      .95 
  108.13   141.10   190.11   209.50   241.54 

lowest :  90.99  93.19  95.82  98.46 105.49, highest: 199.12 200.00 211.87 244.84 282.64
--------------------------------------------------------------------------------
prot 
        n   missing  distinct      Info      Mean       Gmd       .05       .10 
       12        11        10     0.993      3599      7188     4.735     4.787 
      .25       .50       .75       .90       .95 
    4.910     5.085     5.527     6.165 19412.343 

lowest :     4.68     4.78     4.85     4.93     5.02
highest:     5.15     5.33     6.12     6.17 43131.00
                                                                         
Value          4.68     4.78     4.85     4.93     5.02     5.15     5.33
Frequency         1        1        1        2        1        1        2
Proportion    0.083    0.083    0.083    0.167    0.083    0.083    0.167
                                     
Value          6.12     6.17 43131.00
Frequency         1        1        1
Proportion    0.083    0.083    0.083
--------------------------------------------------------------------------------
urea 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      15        8       15        1     57.5    29.49    31.94    35.87 
     .25      .50      .75      .90      .95 
   39.50    50.71    65.73    72.81   101.08 

lowest :  26.02  34.48  37.96  38.23  40.78, highest:  65.20  66.27  66.94  76.73 157.89
                                                                         
Value       26.02  34.48  37.96  38.23  40.78  43.06  45.61  50.71  52.32
Frequency       1      1      1      1      1      1      1      1      1
Proportion  0.067  0.067  0.067  0.067  0.067  0.067  0.067  0.067  0.067
                                                    
Value       60.37  65.20  66.27  66.94  76.73 157.89
Frequency       1      1      1      1      1      1
Proportion  0.067  0.067  0.067  0.067  0.067  0.067
--------------------------------------------------------------------------------
album 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
      11       12       11        1    66.15    9.592    54.06    55.36 
     .25      .50      .75      .90      .95 
   62.12    66.82    69.62    72.14    77.94 

lowest : 52.77 55.36 59.59 64.64 66.27, highest: 67.09 68.59 70.64 72.14 83.73
                                                                            
Value      52.77 55.36 59.59 64.64 66.27 66.82 67.09 68.59 70.64 72.14 83.73
Frequency      1     1     1     1     1     1     1     1     1     1     1
Proportion 0.091 0.091 0.091 0.091 0.091 0.091 0.091 0.091 0.091 0.091 0.091
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Los gráficos de caja de R base también pueden ayudar a tener una rápida visualización de la variable numérica:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(preclin_data7<span class="sc">$</span>prot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="aid_taller_solucionario_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Una vez identificado el dato no plausible, podemos tratar de corregirlo o, si no es posible, eliminarlo.</p>
<p>Por ejemplo, en el caso de la variable <code>prot</code>, el valor <code>43131</code> es una valor extremo que podríamos corregir si tuvieramos esta información. Imaginemos que el valor correcto era de 4.5, esto se podría hacer de la siguiente manera:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>preclin_data7 <span class="sc">%&gt;%</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prot =</span> <span class="fu">recode</span>(prot,  <span class="st">`</span><span class="at">43131</span><span class="st">`</span> <span class="ot">=</span> <span class="fl">4.5</span>)) <span class="ot">-&gt;</span> preclin_data8</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>En el caso no pudieramos corregirlo, podríamos convertirlo en dato faltante con la función <code>na_if()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>preclin_data7 <span class="sc">%&gt;%</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prot =</span> <span class="fu">na_if</span>(prot,  <span class="dv">43131</span>)) <span class="ot">-&gt;</span> preclin_data9</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="paso-5-haga-consultas-para-verificar-consistencias" class="level2">
<h2 class="anchored" data-anchor-id="paso-5-haga-consultas-para-verificar-consistencias">Paso 5: Haga consultas para verificar consistencias</h2>
<p>Podemos hacer algunas consultas o <code>queries</code> usando las funciones de {dplyr}. Veamos algunas consultas de interés:</p>
<section id="a-seleccione-a-los-ratones-de-la-jaula-5-y-muestre-sus-valores-de-glucosa-y-triglicéridos." class="level3">
<h3 class="anchored" data-anchor-id="a-seleccione-a-los-ratones-de-la-jaula-5-y-muestre-sus-valores-de-glucosa-y-triglicéridos.">a) Seleccione a los ratones de la jaula 5 y muestre sus valores de glucosa y triglicéridos.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>preclin_data9 <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(id_jaula <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id_jaula, id_raton, glucose, tag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id_jaula id_raton glucose    tag
1        5       11  113.38 128.35
2        5       12  102.62 282.64
3        5       13   60.10 200.00
4        5       14  150.13 199.12</code></pre>
</div>
</div>
</section>
<section id="b-muestre-qué-ratones-tienen-niveles-de-úrea-mayores-a-60-pero-niveles-de-glucosa-entre-100-y-160-inclusive." class="level3">
<h3 class="anchored" data-anchor-id="b-muestre-qué-ratones-tienen-niveles-de-úrea-mayores-a-60-pero-niveles-de-glucosa-entre-100-y-160-inclusive.">b) Muestre qué ratones tienen niveles de úrea mayores a 60 pero niveles de glucosa entre 100 y 160 inclusive.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>preclin_data9 <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(urea <span class="sc">&gt;</span> <span class="dv">60</span> <span class="sc">&amp;</span> glucose <span class="sc">&lt;=</span> <span class="dv">160</span> <span class="sc">&amp;</span> glucose <span class="sc">&gt;=</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id_jaula id_raton   tratamiento protocolo peso_inicial peso_final peso_utero
1        1        1       control       ovx         26.0      33.28    123.000
2       10       21 sham operated    no ovx         23.4      27.90      0.535
   chol glucose    tag prot  urea album
1 85.99  109.97 182.42   NA 66.27 66.82
2 59.28  126.77 244.84   NA 60.37    NA</code></pre>
</div>
</div>
</section>
</section>
<section id="extra-bonus-crear-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="extra-bonus-crear-pipeline">Extra bonus: Crear pipeline</h2>
<section id="pipeline-crudo" class="level3">
<h3 class="anchored" data-anchor-id="pipeline-crudo">Pipeline crudo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>preclin_data <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(<span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(id_raton <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> protocolo <span class="sc">==</span> <span class="st">"desconocido"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(id_raton <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> id_jaula <span class="sc">==</span> <span class="dv">7</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">urea =</span> <span class="fu">replace</span>(urea, id_raton <span class="sc">==</span> <span class="dv">6</span>, <span class="fl">65.2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na_if</span>(<span class="fu">list</span>(<span class="at">prot =</span> <span class="sc">-</span><span class="dv">999</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na_if</span>(<span class="fu">list</span>(<span class="at">protocolo =</span> <span class="st">"desconocido"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prot =</span> <span class="fu">recode</span>(prot,  <span class="st">`</span><span class="at">43131</span><span class="st">`</span> <span class="ot">=</span> <span class="fl">4.5</span>)) <span class="ot">-&gt;</span> preclin_data_clean</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>preclin_data_clean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id_jaula id_raton               tratamiento protocolo peso_inicial
1         1        1                   control       ovx        26.00
2         1        2                   control       ovx        24.50
3         1        3                   control       ovx        20.40
4         2        4                   control   hemiovx        26.59
5         2        5                   control       ovx        23.50
6         2        6                      maca       ovx        25.00
7         2        7                      maca       ovx        24.80
8         3        8                      maca       ovx        23.20
9         3        9                      maca   hemiovx        22.69
10        3       10                      maca       ovx        23.90
11        5       11             maca + critro      &lt;NA&gt;        21.90
12        5       12             maca + critro       ovx        23.40
13        5       13             maca + critro       ovx        21.90
14        5       14             maca + critro       ovx        22.40
15        8       15 triple dosis maca + citro       ovx        18.90
16        8       16 triple dosis maca + citro       ovx        23.50
17        9       17 triple dosis maca + citro       ovx        24.50
18        9       18 triple dosis maca + citro       ovx        25.30
19        9       19 triple dosis maca + citro       ovx        27.90
20        9       20             sham operated    no ovx        25.50
21       10       21             sham operated    no ovx        23.40
22       10       22             sham operated    no ovx        22.50
23       10       23             sham operated    no ovx        22.90
   peso_final peso_utero    chol glucose    tag prot   urea album
1       33.28    123.000  85.990  109.97 182.42 4.50  66.27 66.82
2       30.50      0.063  94.460   81.62 211.87 4.68  76.73 55.36
3       29.93      0.078  99.670  118.37 195.16   NA  52.32    NA
4       32.19      0.134  83.380   71.91  98.46   NA  50.71    NA
5       30.37      0.052  82.080   95.53 108.13 5.33  26.02    NA
6       30.43      0.055 107.490  160.36 141.10   NA  65.20 72.14
7       28.77      0.064  76.870  195.53  95.82 5.02  40.78 67.09
8       27.30      0.062  95.760  182.41 105.49 6.12  66.94 70.64
9       26.86      0.070  85.340  184.51  90.99   NA     NA 66.27
10      29.10      0.113  82.080  168.50 143.30 4.85  34.48 83.73
11      24.93      0.108  80.781  113.38 128.35   NA     NA    NA
12      26.70      0.022  88.590  102.62 282.64   NA     NA    NA
13      28.67      0.014 104.880   60.10 200.00 5.33  37.96    NA
14      28.37      0.046  70.350  150.13 199.12 4.93  45.61 64.64
15      23.80      0.057  78.170  110.50 114.73 4.78  38.23 52.77
16      26.70      0.065  85.340  144.88 134.51 5.15  43.06 59.59
17      28.77      0.016  64.400  138.85 160.44   NA     NA    NA
18      29.20      0.068  67.100  140.68 127.03   NA     NA    NA
19      29.48      0.076  65.790  114.70 169.67 6.17     NA    NA
20      30.27      0.088  74.260   94.23 185.05 4.93     NA 68.59
21      27.90      0.535  59.280  126.77 244.84   NA  60.37    NA
22      26.68      0.081  68.400   78.22  93.19   NA 157.89    NA
23      27.43      0.176  84.690  125.20 108.13   NA     NA    NA</code></pre>
</div>
</div>
</section>
<section id="pipeline-documentado" class="level3">
<h3 class="anchored" data-anchor-id="pipeline-documentado">Pipeline documentado</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1) Datos crudos</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>preclin_data <span class="sc">%&gt;%</span> </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2) Eliminar duplicados de fila</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(<span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3) Eliminar ratones con ID duplicado</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(id_raton <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> protocolo <span class="sc">==</span> <span class="st">"desconocido"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(id_raton <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> id_jaula <span class="sc">==</span> <span class="dv">7</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 4) Remplazar dato perdido de urea por valor recuperado</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">urea =</span> <span class="fu">replace</span>(urea, id_raton <span class="sc">==</span> <span class="dv">6</span>, <span class="fl">65.2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 5) Convertir a dato perdido valores camuflados (-999, "desconocido")</span></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na_if</span>(<span class="fu">list</span>(<span class="at">prot =</span> <span class="sc">-</span><span class="dv">999</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na_if</span>(<span class="fu">list</span>(<span class="at">protocolo =</span> <span class="st">"desconocido"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 6) Corregir valor extremo no plausible</span></span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prot =</span> <span class="fu">recode</span>(prot,  <span class="st">`</span><span class="at">43131</span><span class="st">`</span> <span class="ot">=</span> <span class="fl">4.5</span>)) <span class="ot">-&gt;</span> preclin_data_clean</span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a>preclin_data_clean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id_jaula id_raton               tratamiento protocolo peso_inicial
1         1        1                   control       ovx        26.00
2         1        2                   control       ovx        24.50
3         1        3                   control       ovx        20.40
4         2        4                   control   hemiovx        26.59
5         2        5                   control       ovx        23.50
6         2        6                      maca       ovx        25.00
7         2        7                      maca       ovx        24.80
8         3        8                      maca       ovx        23.20
9         3        9                      maca   hemiovx        22.69
10        3       10                      maca       ovx        23.90
11        5       11             maca + critro      &lt;NA&gt;        21.90
12        5       12             maca + critro       ovx        23.40
13        5       13             maca + critro       ovx        21.90
14        5       14             maca + critro       ovx        22.40
15        8       15 triple dosis maca + citro       ovx        18.90
16        8       16 triple dosis maca + citro       ovx        23.50
17        9       17 triple dosis maca + citro       ovx        24.50
18        9       18 triple dosis maca + citro       ovx        25.30
19        9       19 triple dosis maca + citro       ovx        27.90
20        9       20             sham operated    no ovx        25.50
21       10       21             sham operated    no ovx        23.40
22       10       22             sham operated    no ovx        22.50
23       10       23             sham operated    no ovx        22.90
   peso_final peso_utero    chol glucose    tag prot   urea album
1       33.28    123.000  85.990  109.97 182.42 4.50  66.27 66.82
2       30.50      0.063  94.460   81.62 211.87 4.68  76.73 55.36
3       29.93      0.078  99.670  118.37 195.16   NA  52.32    NA
4       32.19      0.134  83.380   71.91  98.46   NA  50.71    NA
5       30.37      0.052  82.080   95.53 108.13 5.33  26.02    NA
6       30.43      0.055 107.490  160.36 141.10   NA  65.20 72.14
7       28.77      0.064  76.870  195.53  95.82 5.02  40.78 67.09
8       27.30      0.062  95.760  182.41 105.49 6.12  66.94 70.64
9       26.86      0.070  85.340  184.51  90.99   NA     NA 66.27
10      29.10      0.113  82.080  168.50 143.30 4.85  34.48 83.73
11      24.93      0.108  80.781  113.38 128.35   NA     NA    NA
12      26.70      0.022  88.590  102.62 282.64   NA     NA    NA
13      28.67      0.014 104.880   60.10 200.00 5.33  37.96    NA
14      28.37      0.046  70.350  150.13 199.12 4.93  45.61 64.64
15      23.80      0.057  78.170  110.50 114.73 4.78  38.23 52.77
16      26.70      0.065  85.340  144.88 134.51 5.15  43.06 59.59
17      28.77      0.016  64.400  138.85 160.44   NA     NA    NA
18      29.20      0.068  67.100  140.68 127.03   NA     NA    NA
19      29.48      0.076  65.790  114.70 169.67 6.17     NA    NA
20      30.27      0.088  74.260   94.23 185.05 4.93     NA 68.59
21      27.90      0.535  59.280  126.77 244.84   NA  60.37    NA
22      26.68      0.081  68.400   78.22  93.19   NA 157.89    NA
23      27.43      0.176  84.690  125.20 108.13   NA     NA    NA</code></pre>
</div>
</div>
<p>¡Ahora de click a <code>Render</code> y genere el reporte en *.html!</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>