project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/"
# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

lang: es

website:
  title: "R para Ciencia de Datos en Salud 3"
  site-url: "https://rcds3.inkastats.es/"
  description-meta: "Brindar fundamentos de análisis descriptivo e inferencia estadística aplicado a Ciencias de la Salud"

  favicon: "/files/icon-512-inkastats.png"

  twitter-card:
    image: "/files/social-image-f22.png"
    card-style: summary_large_image
    creator: "@psotob91"
    site: "@psotob91"

  open-graph:
    image: "/files/social-image-f22.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#035861"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Contenido"
        file: content/index.qmd
      - text: "Tareas"
        file: assignment/index.qmd
      - text: "Ejemplos"
        file: example/index.qmd
      - text: "Recursos"
        file: resource/index.qmd
      - icon: discord
        href: "https://discord.gg/jRnxKhnE"
        aria-label: Discord
      - icon: cloud-fill
        href: "https://www.google.com"
        aria-label: RStudio.cloud

  sidebar:
    - title: "Información general"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - content/index.qmd
        - section: "Contenido del curso"
          contents:
            - text: "1: Introducción a R y RStudio"
              file: content/01-content.qmd
            - text: "2: Análisis descriptivo univariado"
              file: content/02-content.qmd
            - text: "3: Análisis descriptivo bivariado"
              file: content/03-content.qmd
            - text: "4: Reporte descriptivo reproducible"
              file: content/04-content.qmd
            - text: "5: Principios de inferencia estadística"
              file: content/05-content.qmd
            - text: "6: Estimación bajo inferencia clásica"
              file: content/06-content.qmd
            - text: "7: Estimación bajo inferencia por remuestreo"
              file: content/07-content.qmd
            - text: "8: Pruebas de hipótesis: Paradigma clásico y bajo remuestreo"
              file: content/08-content.qmd
            - text: "9: Pruebas de hipótesis para 1 y 2 grupos"
              file: content/09-content.qmd
            - text: "10: Pruebas de hipótesis para 3 o más grupos"
              file: content/10-content.qmd
            - text: "11: Pruebas de hipótesis para proporciones"
              file: content/11-content.qmd
            - text: "12: Intervalos de confianza: buenas prácticas y errores de concepto"
              file: content/12-content.qmd
            - text: "13: Valor p: buenas prácticas y errores de concepto"
              file: content/13-content.qmd
            - text: "14: Reporte reproducible de inferencia estadística"
              file: content/14-content.qmd

    - title: "Tareas"
      contents:
        - section: "Información general"
          contents:
            - assignment/index.qmd
        - section: "Problem sets"
          contents:
            - assignment/01-problem-set.qmd
            - assignment/02-problem-set.qmd
            - assignment/03-problem-set.qmd
            - assignment/04-problem-set.qmd
            - assignment/05-problem-set.qmd
            - assignment/06-problem-set.qmd
            - assignment/07-problem-set.qmd

    - title: "Ejemplos"
      contents:
        - section: "Información general"
          contents:
            - example/index.qmd

    - title: "Recursos"
      contents:
        - section: "Información general"
          contents:
            - resource/index.qmd
            # - resource/r.qmd
            # - resource/style.qmd
            # - resource/data.qmd
            # - resource/citations.qmd
        - section: "Guías"
          contents:
            - resource/manual_installR/install.qmd
          #   - resource/markdown.qmd
          #   - resource/rmarkdown.qmd
          #   - resource/unzipping.qmd
  page-footer:
    left: |
      Contenido {{< fa brands creative-commons >}} {{< var course.copyright_year >}} por [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      Todo el contenido está bajo {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Hecho con {{< fa brands r-project >}} y [Quarto](https://quarto.org/)<br>
      [Ver el código fuente en {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true

