---
title: "<FONT color='#A7D5E8'>Variables y tipos</FONT>"
subtitle: "<FONT color='#E9AFA3' size='10'>R para Ciencia de Datos en Salud: <br> Análisis Descriptivo e Inferencia Estadística</FONT>"
author: "<FONT color='#FFFFFF' size='30'>Percy Soto-Becerra M.D., M.Sc(c)</FONT>"
institute: "<FONT color='#FFFFFF' size='5'>InkaStats Data Science Solutions | Medical Branch<br>@github/psotob91</FONT>"

format: 
  revealjs:
    self-contained: true
    theme: [simple, theme/theme.scss]
    footer: "Variables y tipos"
    slide-number: c/t
    logo: img/logo.png
    width: 1920
    height: 1080
    highlight-style: ayu-dark
    self-contained-math: true
from: markdown+emoji
execute:
  echo: true
---

```{r}
#| label: setup
#| include: false
library(fontawesome)
library(tidyverse)
library(quarto)
library(gt)
library(gtExtras)
library(gtsummary)
library(showtext)
library(kableExtra)
## Ver QUARTO RSTUDIO CONFERENCE: https://github.com/rstudio-conf-2022/get-started-quarto/blob/main/materials/02-authoring.qmd
## 
## blackboard theme: https://github.com/schochastics/quarto-blackboard-theme
## 
## https://github.com/schochastics/xaringan-themes
```

---

# Variables

---

## Tipos de variables 

```{mermaid}
%%| fig-width: 20
%%| fig-align: center
%%| mermaid-format: svg
graph TD
    A[Variables] -->|De acuerdo a su naturaleza| B(Tipos)
    B--> C[Numéricas]
    B--> D[Categóricas]
    C--> E(Continuas)
    C--> F(Discretas)
    D--> G(Politómicas o Multinomiales)
    D--> H(Dicotómica o Binaria)
```

---

## Niveles de medición

```{r}
#| echo: false
var_escalas <- data.frame(
  Nivel = c("Nominal", "Ordinal", "Intervalo", "", "", "Razón", ""), 
  Características = c("Solo distingue nombres.", "Distingue nombres y orden.", 
                      "Distingue nombres, orden y proporciona 'intervalo' de diferencia entre valores.", "Esto implica que cero sea relativo: No indica ausencia, si no que es arbitrario.", "La razón o división no tiene sentido, la resta sí.", "Distingue nombre, orden, proporciona 'intervalo' de diferencia entre valores y el cero es absoluto.", "Esto implica que la diferencia y la razón tienen sentido."), 
  Ejemplo = c("Tratamiento recibido, color de ojos, de cabello, etc.", "Nivel de dolor", "Temperatura en grados Celsius", "", "", "Peso, talla, etc.", "")
)

var_escalas %>% 
  kbl() %>%
  # kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), 
  #               full_width = T) %>% 
  kable_paper("striped", full_width = F) %>%               
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")  %>% 
  row_spec(0, background = "black", color = "white", bold = TRUE) %>% 
  row_spec(c(1, 3:5), background = "#D7261E", color = "white", bold = TRUE) %>% 
  row_spec(c(2, 6, 7), background = "blue", color = "white", bold = TRUE)
```

---

## Tipos y Niveles de medición

```{r}
# var_escalas <- data.frame(
#   Nivel = c("Razón", "Intervalo", "Ordinal", "Nominal"), 
#   Continua = c(""), 
#   Discreta = c(), 
#   Politómica = c(), 
#   Dicotómica = c()
# )
```


---

## Variables numéricas

---

## Variables numéricas